rm: cannot remove ‘logs/M87v2_wide_m4.mem’: No such file or directory
/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:46: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:329: UserWarning: Extinction files not found in extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))
Traceback (most recent call last):
  File "/n/home01/bcook/.conda/envs/py36/bin/pcmd_integrate", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/bin/pcmd_integrate", line 78, in <module>
    data = np.atleast_2d(np.loadtxt(data_file, unpack=True))  # Data columns are Mag-Color
  File "/n/home01/bcook/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 917, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/n/home01/bcook/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/n/home01/bcook/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
OSError: ../data/M87_v2/pcmds/M87_I_gI_wide.pcmd not found.
