/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:46: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/n/home01/bcook/.conda/envs/py36/lib/python3.6/site-packages/pysynphot/locations.py:329: UserWarning: Extinction files not found in extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))
Please wait while the GPU states are initializedPlease wait while the GPU states are initializedTraceback (most recent call last):
  File "/n/home01/bcook/.conda/envs/py36/bin/pcmd_integrate", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/bin/pcmd_integrate", line 129, in <module>
    fit_model.nested_integrate(**args)
  File "/n/home01/bcook/pCMDs/pixcmd/pcmdpy/pcmdpy/sampling/fit_model.py", line 121, in nested_integrate
    sampler.run_nested(**run_kwargs)
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 1649, in run_nested
    return_vals=True)
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 264, in stopping_function
    outputs = list(M(_kld_error, args))
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 59, in _kld_error
    approx=approx)
  File "/n/home01/bcook/dynesty/dynesty/utils.py", line 1064, in kld_error
    new_res = jitter_run(res, rstate=rstate, approx=approx)
  File "/n/home01/bcook/dynesty/dynesty/utils.py", line 320, in jitter_run
    logdvols = misc.logsumexp(a=np.c_[logvols_pad[:-1], logvols_pad[1:]],
AttributeError: module 'scipy.misc' has no attribute 'logsumexp'
